baseURL = "https://henvic.dev/"
languageCode = "en-us"
title = "Henrique Vicente"
theme = "henvic"
sectionPagesMenu = "main"
googleAnalytics = "UA-43519325-1"
pygmentsStyle = "monokai"

[markup]
  [markup.highlight]
    tabWidth = 8
    lineNos = true
    # see https://gohugo.io/getting-started/configuration-markup/#configure-markup
    # see https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 4
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    identifier = "portfolio"
    weight = 5
  [[menu.main]]
    name = "Open Source"
    url = "/opensource/"
    weight = 6
  [[menu.main]]
    name = "Favorites"
    url = "/favorites/"
    weight = 7

  [[menu.main]]
    name = "httpretty"
    url = "/portfolio/#httpretty"
    parent = "portfolio"
    weight = 400

  [[menu.main]]
    name = "WeDeploy CLI Tool"
    url = "/portfolio/#wedeploy"
    parent = "portfolio"
    weight = 401

  [[menu.main]]
    name = "Vehikel"
    url = "/portfolio/#vehikel"
    parent = "portfolio"
    weight = 402

[[menu.main]]
    name = "Tic-tac-toe"
    url = "/portfolio/#tic-tac-toe"
    parent = "portfolio"
    weight = 403

[[menu.main]]
    name = "accidents"
    url = "/portfolio/#accidents"
    parent = "portfolio"
    weight = 504

[[menu.main]]
    name = "to-post.it"
    url = "/portfolio/#topostit"
    parent = "portfolio"
    weight = 505

[[menu.main]]
    name = "trazqueeupago.com"
    url = "/portfolio/#trazqueeupago"
    parent = "portfolio"
    weight = 506

[[menu.main]]
    name = "Cahier"
    url = "/portfolio/#cahier"
    parent = "portfolio"
    weight = 507

[[menu.main]]
    name = "Plifk"
    url = "/portfolio/#plifk"
    parent = "portfolio"
    weight = 508
